# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright OxidOS Automotive SRL 2024
#
# Author: Irina Nita <irina.nita@oxidos.io>
# Author: Darius Jipa <darius.jipa@oxidos.io>

[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
parse = { path = "../../parse" }
serde = { version = "1.0.197", default-features = false, features = [
    "derive",
    "alloc",
] }
quote = "1.0.36"
